version: "3.9"

services:
  mysql:
    container_name: watch_one_db
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - watch_one_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: watch_one
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root

volumes:
  watch_one_db: